use_frameworks!

platform :ios, '9.0'

target 'CTSConnectedDevices_Example' do
  pod 'CTSConnectedDevices', :path => '../'

  target 'CTSConnectedDevices_Tests' do
    inherit! :search_paths

    
  end
end
